typography_spectrum: 0.8891495731659234
color:
  brandStrength: 0.4849003052804619
  lightness: 0.879806641722098
  saturation: 0.04493180220015347
  rhythmicContrast: 0.1834660170134157
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.7357059384230524
author:
  name: Tony Sherman
  email: tony@impactteams.com
  url: www.impactteams.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/681c7ce2-8e08-42f5-af42-63e6ed1ee13d.png
name: Impact Teams
title: Sharpening your competitive edge
